sudo: required
services:
- docker
env:
  global:
  - PAPERLESS_VERSION=${PAPERLESS_VERSION:-2.7.0}
  - BUILD_DATE=$(date +"%Y-%m-%d")
  - BUILD_TYPE=stable
  - secure: DiCiZq09OojV0Mj+6kbk9K37nJVhIxkoiUVP5nB9Vvk9fLm6Q5wSe0VlDU8DFurYsXt0sw9QIeuOsy1GdP2gW2E2T0Ld2sZgiFCxnp4s1hf3Uo93IPsjIdngu2B85lDxqXp6MHGEOZEuTFsTdU0E89W4Upm3tJvUH3r6C5d0NdKYEFG7ItKYnHSlMozjTRp/mCXZB/MLp8oPk4UmFeTquLE4pRWCoznpzE6kESo6g5BVR+Xx6Ww1UX8/RD4dxW1H5I0Q6TODnjlYX8Cljr4e3EDaZTvAGnsNLLmfi8xdd7CB7qSiI9JSd6w11JVLFy4WNhPNMLa4rC6ERQubACJxQQ9GNdaMm24taMbUt6dyuSBvPJpFju6cypBvixL2017dcd1Wo+6X3FwMVTkkJA75bK7dfzSVdkunAJtRl4+STVGBvBiNkGCttWRjobBAVK97JkDGWZSDWyHlAcnHZzCvQCqDm5jwc3U9BoJo8De8LWIFE1OTxbUmvU4lhG9zQFQzeMX4FlD8h0BipASvPa90d6yrq/3YuF1OdPoBiQcBN+iTpv8pxsRIn0EIXB2c9PXE8RseBgSXViBq845vOOQx19GhGBYWJIXnORrOcXbyEXcHzbSt8fdnwpGn8tUuXRpKBg6fkQ6bbX44Ma3uO3aoJeb9PLDo1Z1nqoWrxWF8a0M=
jobs:
  include:
  - stage: build
    script:
    - make
  - stage: build and test
    script:
    - make compose-file
    - docker-compose build
    - docker-compose up -d
    - sleep 15s
    - make test
    - docker-compose kill
    - docker-compose down
  - stage: build and push docker image
    script:
    - make
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker tag  ${USER}/paperless:latest ${DOCKER_USERNAME}/docker-paperless:${PAPERLESS_VERSION}
    - docker push ${DOCKER_USERNAME}/docker-paperless:${PAPERLESS_VERSION}
    - docker tag  ${DOCKER_USERNAME}/docker-paperless:${PAPERLESS_VERSION} ${DOCKER_USERNAME}/docker-paperless:latest
    - docker push ${DOCKER_USERNAME}/docker-paperless:latest
    - docker logout
