---
version: '2.1'

services:

  consumer:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_DATE
        - BUILD_VERSION
        - BUILD_TYPE
        - PAPERLESS_VERSION
    container_name: paperless_consumer
    hostname: paperless_consumer
    # uncomment the following line to start automatically on system boot
    # restart: always
    depends_on:
      webserver:
        condition: service_healthy
    volumes:
      - data:${PAPERLESS_HOME}/data
      - media:${PAPERLESS_HOME}/media
      # This should be set to the same value as the consume directory
      # in the webserver service above.
      - ./consume:/consume
      # Likewise, you can add a local path to mount a directory for
      # exporting. This is not strictly needed for paperless to
      # function, only if you're exporting your files: uncomment
      # it and fill in a local path if you know you're going to
      # want to export your documents.
      # - /path/to/another/arbitrary/place:/export
    env_file: docker-compose.env
    command: ["document_consumer"]
