---
version: '2.1'

services:
  webserver:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        - BUILD_DATE
        - BUILD_VERSION
        - BUILD_TYPE
        - PAPERLESS_VERSION
    # uncomment the following line to start automatically on system boot
    # restart: always
    ports:
      # You can adapt the port you want Paperless to listen on by
      # modifying the part before the `:`.
      - "8080:8000"
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      # You have to adapt the local path you want the consumption
      # directory to mount to by modifying the part before the ':'.
      - ./consume:/consume
    env_file: docker-compose.env
    # The reason the line is here is so that the webserver that doesn't do
    # any text recognition and doesn't have to install unnecessary
    # languages the user might have set in the env-file by overwriting the
    # value with nothing.
    environment:
      - PAPERLESS_OCR_LANGUAGES=
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]
