#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF > .env

BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
PAPERLESS_VERSION=${PAPERLESS_VERSION}

EOF

cp docker-compose_example.env compose/docker-compose.env

docker-compose \
  --file compose/head.yml \
  --file compose/webserver.yml \
  --file compose/consumer.yml \
  config > docker-compose.yml
