#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

PAPERLESS_VERSION=2.6.0

echo "VCS_REF=${GIT_SHA1}" > .env
echo "BUILD_DATE=${BUILD_DATE}" >> .env
echo "BUILD_VERSION=${BUILD_VERSION}" >> .env
echo "BUILD_TYPE=stable" >> .env
echo "PAPERLESS_VERSION=${PAPERLESS_VERSION}" >> .env

cp docker-compose_example.env docker-compose.env

docker-compose \
  --file docker-compose_example.yml \
  config > docker-compose.yml
